## Oscilation Analysis

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
station_metadata = pd.read_csv('/Users/dlugardo/Documents/GitHub/signal-processing-enu/LTM/LTM_station_metadata.csv')

   station  start_date    end_date  years_of_data
0     JWLF  2014-08-18  2025-03-02          10.54
1     JGBL  2014-08-17  2025-03-02          10.54
2     THU2  2003-01-01  2014-12-04          11.92
3     NNVN  2014-09-02  2025-03-02          10.50
4     YMER  2009-08-18  2025-03-02          15.54
5     KMOR  2007-09-03  2025-03-02          17.49
6     BLAS  2014-08-21  2025-03-02          10.53
7     KLSQ  2014-06-15  2025-03-03          10.72
8     MARG  2007-08-30  2025-03-02          17.51
9     HRDG  2014-08-17  2025-03-02          10.54
10    KELY  2010-03-20  2018-05-30           8.19
11    ILUL  2011-06-27  2024-11-23          13.41
12    KBUG  2014-08-31  2025-03-02          10.50
13    DGJG  2009-08-11  2025-03-02          15.56
14    WTHG  2009-08-13  2025-03-02          15.55
15    AASI  2009-01-07  2023-08-20          14.61
16    HJOR  2014-08-31  2025-03-02          10.50
17    DMHN  2011-11-17  2018-12-15           7.08
18    GROK  2011-08-21  2025-03-02          13.53
19    TREO  2007-09-01  2014-05-08           6.68
20    HMBG  2009-08-12  2025-03-02          15.55
21    PAMI  2018-04-13  2023-09-14           5.42
22    SISI  2013-02-25  2021-01-29           7.93
23    DKSG  2014-08-12  2025-03-02          10.55
24    QEQE  2018-09-07  2023-11-21           5.20
25    KULL  2007-08-15  2013-08-16           6.00
26    QAQ1  2009-10-01  2019-03-11           9.44
27    SCOR  2016-10-23  2025-03-03           8.36
28    KAGA  2013-01-06  2025-03-02          12.15
29    TIN1  2019-08-28  2025-03-03           5.51
30    LEFN  2008-07-03  2022-12-11          14.44
31    GMMA  2019-08-18  2025-03-02           5.54
32    LBIB  2015-08-18  2023-02-25           7.52
33    SCBY  2014-08-16  2025-03-02          10.54
34    MSVG  2009-08-10  2025-03-02          15.56
35    KMJP  2014-08-18  2025-03-01          10.54
36    NORD  2019-08-23  2025-03-03           5.53
37    VFDG  2009-08-08  2025-03-02          15.56
38    UPVK  2011-09-07  2025-03-03          13.49
39    DANE  2018-08-02  2025-03-02           6.58
40    QAAR  2013-12-24  2025-03-03          11.19
41    SRMP  2007-08-13  2025-03-02          17.55
42    SENU  2008-05-16  2014-04-13           5.91
43    KSNB  2007-08-20  2025-03-02          17.53
44    PLPK  2017-05-18  2025-02-21           7.76
45    LYNS  2007-08-29  2018-02-14          10.46
46    KAGZ  2018-02-23  2025-01-08           6.87
47    HEL2  2007-08-24  2013-05-15           5.72
48    ASKY  2014-08-12  2025-03-02          10.55
49    NUUK  2009-01-31  2025-03-03          16.08
50    UTMG  2013-06-09  2025-03-02          11.73
51    MIK2  2009-08-08  2017-03-09           7.58
52    KUAQ  2019-07-31  2024-08-04           5.01
53    RINK  2007-08-30  2025-03-01          17.50
54    NRSK  2014-08-20  2025-03-02          10.53

In [4]:
stations_long = []

In [ ]:
stations_long = station_metadata.loc[
    station_metadata['years_of_data'] >= 10, 'station'].unique().tolist()

In [ ]:
for station in stations_long: